# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y8ydOEB2MzWLFzW1tv7cUDS75fW3I74w
"""

import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# PARAMETERS
# -----------------------------
N = 15                 # grid size
T = 5000               # number of drive steps
zc = 4                 # critical threshold
seed = 42
np.random.seed(seed)

# connectivity options
CONNECTIVITY_CASES = {
    "k4_VonNeumann": [(-1,0),(1,0),(0,-1),(0,1)],
    "k8_Moore": [(-1,0),(1,0),(0,-1),(0,1),
                 (-1,-1),(-1,1),(1,-1),(1,1)]
}

# -----------------------------
# TOPPLING FUNCTION
# -----------------------------
def topple(grid, neighbors):
    avalanche_size = 0

    while np.any(grid >= zc):
        unstable = np.argwhere(grid >= zc)

        for i, j in unstable:
            grid[i, j] -= len(neighbors)
            avalanche_size += 1

            for di, dj in neighbors:
                ni, nj = i + di, j + dj

                # open boundary (dissipation)
                if 0 <= ni < N and 0 <= nj < N:
                    grid[ni, nj] += 1

    return avalanche_size

# -----------------------------
# SIMULATION FUNCTION
# -----------------------------
def run_simulation(neighbors):
    grid = np.zeros((N, N), dtype=int)
    avalanche_sizes = []
    topple_map = np.zeros((N, N))

    for step in range(T):
        # slow driving (random fouling deposition)
        i, j = np.random.randint(0, N, size=2)
        grid[i, j] += 1

        # avalanche event
        size_before = np.sum(topple_map)
        avalanche = topple(grid, neighbors)
        avalanche_sizes.append(avalanche)

    return grid, avalanche_sizes, topple_map

# -----------------------------
# RUN BOTH CONNECTIVITY CASES
# -----------------------------
results = {}

for case, neighbors in CONNECTIVITY_CASES.items():
    print(f"Running simulation for {case}...")
    grid, avalanches, topple_map = run_simulation(neighbors)
    results[case] = (grid, avalanches)

# -----------------------------
# PLOT STEADY STATE GRID
# -----------------------------
plt.figure(figsize=(10,4))
for idx, (case, (grid, avalanches)) in enumerate(results.items()):
    plt.subplot(1,2,idx+1)
    plt.imshow(grid, cmap='plasma')
    plt.title(f"Steady State Fouling ({case})")
    plt.colorbar(label="Fouling Load")

plt.tight_layout()
plt.show()

# -----------------------------
# AVALANCHE DISTRIBUTION PLOT
# -----------------------------
plt.figure(figsize=(6,5))

for case, (grid, avalanches) in results.items():
    avalanches = np.array(avalanches)
    avalanches = avalanches[avalanches > 0]

    hist, bins = np.histogram(avalanches, bins=40, density=True)
    centers = (bins[:-1] + bins[1:]) / 2

    plt.loglog(centers, hist, 'o', label=case)

plt.xlabel("Avalanche Size (s)")
plt.ylabel("P(s)")
plt.title("Power-law Avalanche Distribution")
plt.legend()
plt.grid(True)
plt.show()

# -----------------------------
# RUNNING MEAN PLOT
# -----------------------------
plt.figure(figsize=(6,5))

for case, (grid, avalanches) in results.items():
    avalanches = np.array(avalanches)
    running_mean = np.cumsum(avalanches) / np.arange(1, len(avalanches)+1)
    plt.plot(running_mean, label=case)

plt.xlabel("Avalanche Index")
plt.ylabel("Running Mean Size")
plt.title("Convergence to SOC State")
plt.legend()
plt.grid(True)
plt.show()

print("Simulation complete!")